FROM node:20-alpine AS build
WORKDIR /app
COPY . .
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run build 

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY package.json ./
ENV NODE_ENV=production
RUN npm install --production --ignore-scripts
EXPOSE 3000
CMD ["node", "dist/main.js"]
